
export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_SINGLE_MOVIE = 'GET_SINGLE_MOVIE';
export const MAKE_FILTER = 'MAKE_FILTER'
export const GET_COUNTRY_LIST_MOVIES = 'GET_COUNTRY_LIST_MOVIES'
export const GET_CERTIFICATE_BASED_LIST = 'GET_CERTIFICATE_BASED_LIST'
export const GET_GENRE_LIST_MOVIES = 'GET_GENRE_LIST_MOVIES'
export const GET_FILTER_DATA = 'GET_FILTER_DATA'
export const GET_TRENDING = 'GET_TRENDING'

export const RECOMENDED_MOVIES = 'RECOMENDED_MOVIES'

export const FETCH_REQUEST_FAILURE  = 'FETCH_REQUEST_FAILURE'
export const  FETCH_REQUEST = 'FETCH_REQUEST'
export const GET_FEATURED = 'GET_FEATURED'
